/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pack_Herramientas;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author pc
 */
public class JFrame_Main extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        
        //Mostramos en el centro al ejecutar la aplicacion
        this.setLocationRelativeTo(null);
        
        //vinculamos los paneles
        Ping p1 = new Ping();//Instanciamos la clase Ping
        p1.setSize(620, 410);// le asignamos el ancho y el alto del panel
        p1.setLocation(0,0);//Asignamos la posicion del panel
        
        //nombre del panel para hacerlo dinamico
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jPanel_NavBar = new javax.swing.JPanel();
        jPanel_Ping = new javax.swing.JPanel();
        jLabel_Ping = new javax.swing.JLabel();
        jPanel_EscanerPuertos = new javax.swing.JPanel();
        jLabel_EscanerPuerto = new javax.swing.JLabel();
        jPanel1_Separador = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Main.setBackground(new java.awt.Color(30, 34, 64));
        jPanel_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_NavBar.setBackground(new java.awt.Color(22, 24, 44));
        jPanel_NavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Ping.setBackground(new java.awt.Color(22, 24, 44));
        jPanel_Ping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_PingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_PingMouseExited(evt);
            }
        });

        jLabel_Ping.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Ping.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_Ping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pack_img/ping.png"))); // NOI18N
        jLabel_Ping.setText("Ping");
        jLabel_Ping.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Ping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PingLayout = new javax.swing.GroupLayout(jPanel_Ping);
        jPanel_Ping.setLayout(jPanel_PingLayout);
        jPanel_PingLayout.setHorizontalGroup(
            jPanel_PingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Ping, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel_PingLayout.setVerticalGroup(
            jPanel_PingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Ping, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel_NavBar.add(jPanel_Ping, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 30));

        jPanel_EscanerPuertos.setBackground(new java.awt.Color(22, 24, 44));

        jLabel_EscanerPuerto.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_EscanerPuerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pack_img/escaner-puertos.png"))); // NOI18N
        jLabel_EscanerPuerto.setText("Escaner Puertos");
        jLabel_EscanerPuerto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_EscanerPuerto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EscanerPuertoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_EscanerPuertoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_EscanerPuertoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EscanerPuertosLayout = new javax.swing.GroupLayout(jPanel_EscanerPuertos);
        jPanel_EscanerPuertos.setLayout(jPanel_EscanerPuertosLayout);
        jPanel_EscanerPuertosLayout.setHorizontalGroup(
            jPanel_EscanerPuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_EscanerPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel_EscanerPuertosLayout.setVerticalGroup(
            jPanel_EscanerPuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_EscanerPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel_NavBar.add(jPanel_EscanerPuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        jPanel1_Separador.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1_SeparadorLayout = new javax.swing.GroupLayout(jPanel1_Separador);
        jPanel1_Separador.setLayout(jPanel1_SeparadorLayout);
        jPanel1_SeparadorLayout.setHorizontalGroup(
            jPanel1_SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel1_SeparadorLayout.setVerticalGroup(
            jPanel1_SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel_NavBar.add(jPanel1_Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 255));
        jLabel4.setText("Herramientas");
        jPanel_NavBar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("by keytel");
        jPanel_NavBar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 90, -1));

        jPanel_Main.add(jPanel_NavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 150, 460));

        jPanel_Header.setBackground(new java.awt.Color(22, 24, 44));
        jPanel_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pack_img/logout.png"))); // NOI18N
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });
        jPanel_Header.add(jLabel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 20, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pack_img/logo.png"))); // NOI18N
        jPanel_Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 45));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VulHub");
        jPanel_Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jPanel1.setBackground(new java.awt.Color(30, 34, 64));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pack_img/search.png"))); // NOI18N
        jLabel5.setText(" Buscador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel_Header.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 12, 230, 20));

        jPanel_Main.add(jPanel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 45));

        content.setBackground(new java.awt.Color(22, 24, 44));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel_Main.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 620, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        // Cerrar Programa
        System.exit(0);
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel_PingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PingMouseClicked
        // TODO add your handling code here:
        
        Ping p1 = new Ping();//instanciamos el frame Ping para mostrarlo y hacerlo dinamico
        p1.setSize(620, 410);//le asignamos el ancho y el alto del panel
        p1.setLocation(0,0);//posicion donde se mostrara el panel
        
        //nombre del panel para hacerlo dinamico
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jLabel_PingMouseClicked

    private void jLabel_EscanerPuertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EscanerPuertoMouseClicked
        // TODO add your handling code here:
        
        Escanerpuerto p2 = new Escanerpuerto();//instanciamos el frame EscanerPuerto para mostrarlo y hacerlo dinamico
        p2.setSize(620, 410);//le asignamos el ancho y el alto del panel
        p2.setLocation(0,0);//posicion donde se mostrara el panel
        
        //nombre del panel para hacerlo dinamico
        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jLabel_EscanerPuertoMouseClicked

    private void jPanel_PingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_PingMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel_PingMouseEntered

    private void jPanel_PingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_PingMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel_PingMouseExited
    
    //Eventos del NavBar Ping
    private void jLabel_PingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PingMouseEntered
        // TODO add your handling code here:
        jPanel_Ping.setBackground(new Color(30,34,64));
    }//GEN-LAST:event_jLabel_PingMouseEntered

    private void jLabel_PingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PingMouseExited
        // TODO add your handling code here:
        jPanel_Ping.setBackground(new Color(22,24,44));
    }//GEN-LAST:event_jLabel_PingMouseExited

    //Eventos del NavBar Escaner Puertos
    private void jLabel_EscanerPuertoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EscanerPuertoMouseEntered
        // TODO add your handling code here:
        jPanel_EscanerPuertos.setBackground(new Color(30,34,64));
    }//GEN-LAST:event_jLabel_EscanerPuertoMouseEntered

    private void jLabel_EscanerPuertoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EscanerPuertoMouseExited
        // TODO add your handling code here:
        jPanel_EscanerPuertos.setBackground(new Color(22,24,44));
    }//GEN-LAST:event_jLabel_EscanerPuertoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_EscanerPuerto;
    private javax.swing.JLabel jLabel_Ping;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_Separador;
    private javax.swing.JPanel jPanel_EscanerPuertos;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_NavBar;
    private javax.swing.JPanel jPanel_Ping;
    // End of variables declaration//GEN-END:variables
}
