/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pack_Herramientas;


public class Ping extends javax.swing.JPanel {

    /**
     * Creates new form Ping
     */
    public Ping() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField_TTL = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton_Limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_UrlTarget = new javax.swing.JTextField();

        setBackground(new java.awt.Color(22, 24, 44));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PING");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, 1));

        jPanel2.setBackground(new java.awt.Color(30, 34, 64));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Estado:");

        jTextArea.setBackground(new java.awt.Color(30, 34, 64));
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextArea.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 560, 220));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TTL:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextField_TTL.setBackground(new java.awt.Color(30, 34, 64));
        jTextField_TTL.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jTextField_TTL.setForeground(new java.awt.Color(84, 65, 212));
        jTextField_TTL.setBorder(null);
        add(jTextField_TTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 40, 20));

        jButton1.setBackground(new java.awt.Color(85, 66, 214));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENVIAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 130, 30));

        jButton_Limpiar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Limpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarActionPerformed(evt);
            }
        });
        add(jButton_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 100, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ip Host:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextField_UrlTarget.setBackground(new java.awt.Color(30, 34, 64));
        jTextField_UrlTarget.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jTextField_UrlTarget.setForeground(new java.awt.Color(84, 65, 212));
        jTextField_UrlTarget.setBorder(null);
        add(jTextField_UrlTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 500, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Gurados la ip en la variable TargeUrl
        String TargetUrl = jTextField_UrlTarget.getText();
        
        //llamada de Clase Ping
        ClassPing Target = new ClassPing();//Instanciamos la clase ClassPing en Target
        Target.setPing(TargetUrl);// al setPing le mandamos un parametro que es TargetUrl->contiene la ip que ingresamos
        String InfoPing = Target.getInfoPing();//capturamos la informacion en la variable InfoPing que nos retorna el getIngoPing
        
       //Variables del bucle
       int TTL = Integer.parseInt(jTextField_TTL.getText()); //guardamos el valor del TTL ingresado
        //Bucle de Contenido
        String cadena = "";// declaramos una variable de tipo String
        for(int i=0; i<TTL; i++){//si el i es menor que el valor del TTl, el bucle volvera a ejecutar
            cadena += "Conectando: "+InfoPing + "\n"; //Guardamos la informacion del InfoPing y una cadena en la variable cadena
            
        }
        //Mostramos informacion por consola
        
        jTextArea.setText(cadena);//Mostramos los resultados que guarda la variable cadena
       
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
        // TODO add your handling code here:
        //Limpiamos los resultados
        jTextArea.setText("");
    }//GEN-LAST:event_jButton_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField_TTL;
    private javax.swing.JTextField jTextField_UrlTarget;
    // End of variables declaration//GEN-END:variables
}
